version: "3.7"
services:
  php:
    container_name: country-search_php
    build:
      args:
        user: rechi
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: landing-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  nginx:
    container_name: country-search_nginx
    hostname: country-search.localhost
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./docker/logs/:/var/log/nginx/
    ports:
        - 80:80
    environment:
        - NGINX_PORT=80

  mongo:
      image: mongo
      container_name: country-search_mongodb
      restart: always
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: A123456
      ports:
          - 27017:27017
  redis:
      image: redis
      container_name: country-search_redis
      ports:
          - "6379:6379"